spring:
  profiles:
    active: 
    - default
  config:
    import: optional:file:.env[.properties]
  application:
    name: "payment-service"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  
  cloud:
    function:
      definition: orderConsumer;paymentProducer
    stream:
      kafka:
        binder:
          brokers: broker:9092
      bindings:
        orderConsumer-in-0: 
          destination: orders
          group: orderConsumer
        paymentProducer-out-0:
          destination: payments
          group: paymentProducer
        
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      auto-offset-reset:  earliest
      enable-auto-commit: true
      key-deserializer:
        org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer:
        org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer:
        org.apache.kafka.common.serialization.ByteArraySerializer
    

server:
  port: ${PORT}