spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "payment-service"
  # database
  datasource:
    url: jdbc:postgresql://localhost:5433/payment-service
    username: root
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration/
  # cloud streams
  cloud:
    function:
      definition: orderConsumer;paymentProducer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderConsumer-in-0: 
          destination: orders
          group: orderConsumer
        paymentProducer-out-0:
          destination: payments
          group: paymentProducer
        
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset:  earliest
      enable-auto-commit: true
      key-deserializer:
        org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer:
        org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer:
        org.apache.kafka.common.serialization.ByteArraySerializer
     


server:
  port: 7070