spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  threads:
    virtual:
      enabled: true
  cloud:
    stream:
      # function:
      #   definition: orderCreated
      kafka:
        binder:
          brokers:
          - ${BOOTSTRAP_SERVER}
      bindings:
        orders-out-0:
          destination: orders
          group: orderProducers
        paymentProcessed-in-0:
          destination: payments
          group: order-payments
  kafka:
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer:
        org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: ${PORT:8081}
