spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  threads:
    virtual:
      enabled: true
  cloud:
    function:
      definition: paymentConsumer
    stream:
      kafka:
        binder:
          brokers:
          - ${BOOTSTRAP_SERVER}
      bindings:
        orders-out-0:
          destination: orders
          group: orderProducers
        paymentConsumer-in-0:
          destination: payments
          group: order-service-payment-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset:  latest
      enable-auto-commit: true
      key-deserializer:
        org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer:
        org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer:
        org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: ${PORT:8081}
